version: '3.9'
services:
  laravel-php:
    container_name: laravel-opentelemetry-demo-php
    build:
      context: ./
      args:
        APP_ENV: ${APP_ENV}
    env_file:
      - .env
    volumes:
      - ./:/var/www/html
    networks:
      - laravel-opentelemetry-demo
  laravel-nginx:
    container_name: laravel-opentelemetry-demo-nginx
    image: nginx:1.25
    ports:
      - 8000:80
    volumes:
      - ./public:/var/www/html
      - ./build/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel-opentelemetry-demo
  zipkin:
    container_name: zipkin-demo
    image: openzipkin/zipkin
    ports:
      - 9411:9411
    networks:
      - laravel-opentelemetry-demo
networks:
  laravel-opentelemetry-demo:
    driver: bridge
